DROP DATABASE IF EXISTS employeeTracker_db;

CREATE DATABASE employeeTracker_db;

USE employeeTracker_db;

CREATE TABLE employees(
id INT NOT NULL AUTO_INCREMENT,
firstName VARCHAR(30) NOT NULL,
lastName VARCHAR(30) NOT NULL,
roleId INT NOT NULL,
managerId INT,
PRIMARY KEY (id)
);

CREATE TABLE roles(
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR(30) NOT NULL,
salary DECIMAL NOT NULL, 
departmentId INT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE departments(
id INT NOT NULL AUTO_INCREMENT,
deptName VARCHAR(30) NOT NULL,
PRIMARY KEY (id)
);

